version: "3.8"

services:
  app:
    build: ./frontend
    ports:
      - "8146:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - appnet

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: videogamedb
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
