sonar.projectKey=video-game-crud
sonar.projectName=Video Game CRUD
sonar.organization=default

sonar.host.url=http://localhost:8151
sonar.login=${SONAR_TOKEN}

sonar.sources=backend
sonar.sourceEncoding=UTF-8
